#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port2,           Right,         tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, None)
#pragma config(Motor,  port10,          Left,          tmotorVex393_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

typedef enum {
	DRIVE_FWD,
	DRIVE_BACK,
	TURN_RIGHT
}T_State;

task main(){

	T_State robot_state = DRIVE_FWD;

	while(true){

		switch (robot_state) {
			//robot drives forward
		case DRIVE_FWD:
			motor[Right]=50;
			motor[Left]=65;
			//if robot is too close to a wall, drive back
			if (SensorValue[sonarSensor] < 25 && SensorValue[sonarSensor] >= 0){
				robot_state = DRIVE_BACK;
			}
			break;

		case DRIVE_BACK:
			clearTimer(T1);
			while(time1[T1]<500){
				motor[Right]=-25;
				motor[Left]=-30;
			}
			clearTimer(T1);
			robot_state=TURN_RIGHT;
			break;
			//turn after driving back
		case TURN_RIGHT:
			motor[Right] = -50;
			motor[Left] = 50;
			wait1Msec(1000);
			clearTimer(T1);
			robot_state = DRIVE_FWD; //robot goes back to driving forward
			break;

		default:
			robot_state=DRIVE_FWD;
			break;
		}
	}
}
