#pragma config(Sensor, in1,    IRSensor1,      sensorReflection)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl11, redLED,         sensorDigitalOut)
#pragma config(Sensor, dgtl12, whiteLED,       sensorDigitalOut)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int light_threshold = 80;


typedef enum {
	CHECK = 0,
} T_State;

bool monitorLight(){
	static int minLevelIR1 = 4096;	// Minimum light level seen by IR sensor 1
	static int maxLevelIR1 = 0;			// Maximum light level seen by IR sensor 1
	static int diffLevelIR1 = 0;		// Delta between maximum and minimum seen in last 0.1 seconds

	int lightLevel1 = SensorValue[IRSensor1];
	bool returnValue;

	// Check if 100 msecs have elapsed.
	if ( time1[T1] > 100 )  {
		// 100 msecs have elapsed.  Compute delta of light level.
		diffLevelIR1 = maxLevelIR1 - minLevelIR1;
		// Reset calculation for next 100 msecs.
		maxLevelIR1 = 0;
		minLevelIR1 = 4096;
		clearTimer(T1);

		} else {

		// Check for new minimum/maximum light levels.
		if ( lightLevel1 < minLevelIR1 ) {
			minLevelIR1 = lightLevel1;
			} else if ( lightLevel1 > maxLevelIR1 ) {
			maxLevelIR1 = lightLevel1;
		}
	}
	// Check if light level difference over threshold.
	if ( diffLevelIR1 > light_threshold ) {
		returnValue = true;
		} else {
		returnValue = false;
	}
	return(returnValue);
}




task main(){

	// default states
	T_State robot_state = CHECK;


	while(true){

		switch(robot_state){

		case CHECK:
			//can see beacon but too far for connection
			if(SensorValue[sonarSensor]>13 && monitorLight()){
				SensorValue[whiteLED] = 0;
				SensorValue[redLED] = 1;
				//too close for connection
				} else if(SensorValue[sonarSensor]<9 && monitorLight()){
				SensorValue[whiteLED] = 1;
				SensorValue[redLED] = 0;
				//perfect distance for connection
				}	else if(SensorValue[sonarSensor]<=12 && SensorValue[sonarSensor]>= 10 && monitorLight()){
				SensorValue[whiteLED] = 1;
				SensorValue[redLED] = 1;
			}
			robot_state = CHECK;

			break;
		}
	}
}
